// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TokenManager is an autogenerated mock type for the TokenManager type
type TokenManager struct {
	mock.Mock
}

type TokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenManager) EXPECT() *TokenManager_Expecter {
	return &TokenManager_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function with given fields: userID
func (_m *TokenManager) CreateToken(userID uuid.UUID) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type TokenManager_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *TokenManager_Expecter) CreateToken(userID interface{}) *TokenManager_CreateToken_Call {
	return &TokenManager_CreateToken_Call{Call: _e.mock.On("CreateToken", userID)}
}

func (_c *TokenManager_CreateToken_Call) Run(run func(userID uuid.UUID)) *TokenManager_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *TokenManager_CreateToken_Call) Return(_a0 string, _a1 error) *TokenManager_CreateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenManager_CreateToken_Call) RunAndReturn(run func(uuid.UUID) (string, error)) *TokenManager_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenManager creates a new instance of TokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManager {
	mock := &TokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
